name: Sync main to develop

on:
  push:
    branches:
      - main

jobs:
  merge-main-into-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "zemios"
          git config user.email "zemios@proton.me"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout develop branch
        run: git checkout develop

      - name: Merge main into develop
        run: |
          git merge origin/main --no-edit || echo "No changes to merge"
          git push origin develop
